#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun  02_Convolution.cntk  "forceDeterministicAlgorithms=true stderr=- train=[SGD=[maxEpochs=5]]"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
